"""add point pos

Revision ID: be93cfc0a30c
Revises: ed316346dcb5
Create Date: 2018-07-01 12:57:00.263953

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be93cfc0a30c'
down_revision = 'ed316346dcb5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Points', sa.Column('location', sa.String(length=200), nullable=False))
    op.add_column('Points', sa.Column('position', sa.JSON(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Points', 'position')
    op.drop_column('Points', 'location')
    # ### end Alembic commands ###
