"""categories_diff

Revision ID: ed316346dcb5
Revises: 6b896f8075c6
Create Date: 2018-06-24 19:14:28.364231

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ed316346dcb5'
down_revision = '6b896f8075c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('PointCategories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('point_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['Categories.id'], ),
    sa.ForeignKeyConstraint(['point_id'], ['Points.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('point_id', 'category_id')
    )
    op.create_table('TrackCategories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('track_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['Categories.id'], ),
    sa.ForeignKeyConstraint(['track_id'], ['Tracks.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('track_id', 'category_id')
    )
    op.create_table('TrackPoints',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('track_id', sa.Integer(), nullable=False),
    sa.Column('point_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['point_id'], ['Points.id'], ),
    sa.ForeignKeyConstraint(['track_id'], ['Tracks.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('track_id', 'point_id')
    )
    op.drop_column('Points', 'categories')
    op.drop_column('Tracks', 'categories')
    op.drop_column('Tracks', 'points')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Tracks', sa.Column('points', postgresql.ARRAY(postgresql.JSON(astext_type=sa.Text())), autoincrement=False, nullable=True))
    op.add_column('Tracks', sa.Column('categories', postgresql.ARRAY(postgresql.JSON(astext_type=sa.Text())), autoincrement=False, nullable=True))
    op.add_column('Points', sa.Column('categories', postgresql.ARRAY(postgresql.JSON(astext_type=sa.Text())), autoincrement=False, nullable=True))
    op.drop_table('TrackPoints')
    op.drop_table('TrackCategories')
    op.drop_table('PointCategories')
    # ### end Alembic commands ###
